version: "3.8"

services:
  localstack:
    image: nahuelnucera/ministack
    container_name: ministack-demo
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOG_LEVEL=DEBUG
      - LAMBDA_EXECUTOR=docker
      - PERSIST=1
      - S3_PERSIST=1
      - MINISTACK_REGION=eu-central-1
    volumes:
      - "./volume:/tmp/ministack-data/s3"
      - "/var/run/docker.sock:/var/run/docker.sock"
